version: '2'
services:
    useraccess-app:
        image: useraccess
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://useraccess-mysql:3306/useraccess?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8083:8083
    useraccess-mysql:
        extends:
            file: mysql.yml
            service: useraccess-mysql
